sonar.projectKey=fullStack_portfolio
sonar.projectName=fullStack_portfolio
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.modules=backend,frontend

# Backend
backend.sonar.projectKey=portfolio-backend
backend.sonar.projectBaseDir=Backend
backend.sonar.sources=src
backend.sonar.exclusions=**/node_modules/**,**/coverage/**,**/tests/**
backend.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Frontend
frontend.sonar.projectKey=portfolio-frontend
frontend.sonar.projectBaseDir=Frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/node_modules/**,**/dist/**,**/assets/**