# =============================================================================
# GRAFANA - Configuration personnalisée
# =============================================================================
[server]
protocol = http
http_port = 3000
domain = localhost
root_url = %(protocol)s://%(domain)s:%(http_port)s/

[security]
admin_user = admin
admin_password = p@sser123
allow_embedding = true

[users]
allow_sign_up = false
auto_assign_org = true
auto_assign_org_role = Viewer

[auth.anonymous]
enabled = false

[dashboards]
default_home_dashboard_path = /var/lib/grafana/dashboards/system-overview.json

[alerting]
enabled = false

[unified_alerting]
enabled = true

[smtp]
enabled = false
# host = smtp.example.com:587
# user = alerting@example.com
# password = secret
# from_address = grafana@portfolio.local

[log]
mode = console
level = info
